default: &default
  adapter: postgresql
  encoding: utf8
  url: <%= ENV.fetch("DATABASE_URL") %>
  pool: 5
  username: ept
  password: managu
  port: 5432

development:
  <<: *default
  database: ept_development

test:
  <<: *default
  database: ept_test

production:
  <<: *default
  database: ept_production
  pool: <%= ENV.fetch('WEB_CONCURRENCY_MAX_THREADS') { 32 }.to_i %>
